### ISSUE TITLE
React routing is not supporting deployments under path.

### ISSUE THREAD

**Issue by ioanb7** [rafalp/Misago#619]
Hi Rafal,

I've moved the forum away from root / to /forum/ and now the index disappears.

![Image of the error](https://i.gyazo.com/96f8dd163c253caef74892222d8eb9ae.gif)

Here are the files I've changed in `settings.py`:

```
STATIC_URL = '/forum/static/'
MEDIA_URL = '/forum/media/'
```

And in `urls.py`:

```
url(r'^forum/', include('misago.urls', namespace='misago')),

    # Javascript translations
    url(r'^forum/django-i18n.js$', javascript_catalog),
    url(r'^forum/moment-i18n.js$', momentjs_catalog),
```

Regards,
Ioan.

**Comment by rafalp** [comment]
Nice catch. This is actually bug with our frontend (notice flash of static content before react-router kicks in razes it with blank page for blank route).

I'll fix it in few hours and push after I'll wrap up `[quote][/quote]` tags in new parser.

**Comment by rafalp** [comment]
Fixed on master

**Comment by ioanb7** [comment]
Hi,

The error is back.

https://github.com/rafalp/Misago/blob/master/misago/templates/misago/base.html#L43

There is an absolute path in, so when I change the urls to /forum/_, the whole JS architecture fails.

**Comment by rafalp** [comment]
Pull request is welcome, thanks.

**Comment by ioanb7** [comment]
Thank you Rafal.
